### PR TITLE
Avoid using chdir since the behavior is unexpected now

### PR DESCRIPTION
**Pull request by dulaccc**
Well you know what the issue is.
I hope my fix seems reasonable enough

Cheers

### CODE REVIEW

**Comment by neonichu** [comment]
Thanks for the PR, but I think using CP 1.1 rc1 already fixes this.

**Comment by dulaccc** [comment]
Actually it's was still failing on my machine with CP `1.1.0.rc.1` (I saw your PR on the pthread chdir).
That's why I did this PR

**Comment by drewcrawford** [comment]
still an issue in cocoapods-1.1.0.rc.2

**Comment by bestwnh** [comment]
same issue  in cocoapods-1.1.0.rc.2.

**Comment by sanekgusev** [comment]
The fix looks reasonable and trivial enough. Can it be merged? 
Together with https://github.com/CocoaPods/Rome/pull/46, would make a great v0.8.0. 🚢

**Comment by istx25** [comment]
👍 Please merge. I love Rome and can't use it.

**Comment by segiddins** [comment]
Thanks!

**Comment by istx25** [comment]
Yay, thanks @segiddins. 🎉 Will this automatically be update the Gem?

**Comment by segiddins** [comment]
@istx25 no, but I can take a look at doing a release later in the week

**Pull request merged**
